added more workflow debug

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -112,12 +112,27 @@ jobs:
           OUTPUT="response.html"
 
           wget \
+            -S \
             --max-redirect=20 \
             --output-document="$OUTPUT" \
             "$URL" | true
+      
+      - name: Fetch URL with wget
+        run: curl -v http://localhost:8080/ || true
 
       - name: dump docker logs
         run: docker logs php_apache
+
+      - name: Show Apache + PHP logs
+        run: |
+          echo "=== Apache error.log ==="
+          docker exec php_apache cat /var/log/apache2/error.log || true
+
+          echo "=== Apache access.log ==="
+          docker exec php_apache cat /var/log/apache2/access.log || true
+
+          echo "=== PHP logs (if separate) ==="
+          docker exec php_apache find /var/log -type f -name "*php*" -exec cat {} \; || true
 
       - name: Upload artifact
         uses: actions/upload-artifact@v6
